### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Zacharyflynn06** [learn-co-curriculum/wsl2-env-verification#1]
The instructions "Open your "Terminal" application using "Spotlight Search"" should be for Ubuntu as this is WSL

**Comment by maxwellbenton** [comment]
Hi @Zacharyflynn06!

Thank you for catching this and taking the time to provide feedback! We've updated the first step in this lesson to reference Ubuntu instead of Terminal/Spotlight Search, which should resolve this issue.

The fix has been implemented in the GitHub repository and will be updated for all future students using this lesson in Canvas.

Thank you again for contributing to this lesson!
